name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build docker image
      #   uses: docker/build-push-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Print commands
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Token: ${{ secrets.GITHUB_TOKEN }}"

      - name: Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/ahhda/robot-cow-bot:latest
